#!/usr/bin/env bash
shopt -s extglob
shopt -s nullglob

: ${TOPICS:="homebrew bash aliases git nvm ruby bin atom osx"}
DEST_DIR="$1"
SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#Add helpers to current env
source "$SRC_DIR/script/common.sh"

if [ ! -d "$DEST_DIR" ]
then
   error "No destination was specified.\nExample:\n\n   $ ./install ~\n"
fi

#Temporary files that will be used as buffers
PATH_BUFFER=$(mktemp -t .path-XXXXXXXXX )
ENV_BUFFER=$(mktemp -t .env-XXXXXXXXX )
BASHRC_BUFFER=$(mktemp -t .bashrc-XXXXXXXXX )

cat <<- 'EOF' >> $BASHRC_BUFFER
#######################################################
# This file is automatically managed by tixz/dotfiles #
#######################################################
EOF

echo "source ${DEST_DIR}/.path" >> $BASHRC_BUFFER
echo "source ${DEST_DIR}/.env" >> $BASHRC_BUFFER

for topic in $TOPICS; do
   (
      status "Starting $topic setup"
      INSTALLER="$SRC_DIR/$topic/install.sh"
      CONFIGURE="$SRC_DIR/$topic/configure.sh"
      DOTPATH="$SRC_DIR/$topic/.path"
      DOTENV="$SRC_DIR/$topic/.env"
      DOTBASHRC="$SRC_DIR/$topic/.bashrc"
      DOTRC=( "$SRC_DIR/$topic"/.!(bash)rc )

      #Install
      if [ -f $INSTALLER ]
      then
         status "Starting $topic installation"
         source $INSTALLER
         status "Finished $topic installation"
      fi

      #Configure
      if [ -f $CONFIGURE ]
      then
         status "Starting $topic configuration"
         source $CONFIGURE
         status "Finished $topic configuration"
      fi

      #Buffer path additions
      if [ -f $DOTPATH ]
      then
         echo -e "\n######\n#From: $DOTPATH\n######\n" >> $PATH_BUFFER
         cat $DOTPATH >> $PATH_BUFFER
      fi

      #Buffer other env additions
      if [ -f $DOTENV ]
      then
         echo -e "\n######\n#From: $DOTENV\n######\n" >> $ENV_BUFFER
         cat $DOTENV >> $ENV_BUFFER
      fi

      #Buffer .bashrc additions
      if [ -f $DOTBASHRC ]
      then
         echo -e "\n######\n#From: $DOTBASHRC\n######\n" >> $BASHRC_BUFFER
         cat $DOTBASHRC >> $BASHRC_BUFFER
      fi

      #Copy .*rc files
      if [ -f "${DOTRC[0]}" ]
      then
         cp "${DOTRC[@]}" "$DEST_DIR/"
      fi
      status "Finished $topic setup"
   )
done

echo "####################################################" >> $BASHRC_BUFFER
echo "# Finished installation on:                        #" >> $BASHRC_BUFFER
echo "#     $(          date           )                 #" >> $BASHRC_BUFFER
echo "####################################################" >> $BASHRC_BUFFER

#Write the buffers to their destination
cat $PATH_BUFFER > "$DEST_DIR/.path"
cat $ENV_BUFFER > "$DEST_DIR/.env"
cat $BASHRC_BUFFER > "$DEST_DIR/.bashrc"

if [ "$(uname -s)" == "Darwin" ]
then
  cat <<- EOF > "$DEST_DIR/.bash_profile"
  #OS X doesn't read .bashrc when spawning a new shell
  . "$DEST_DIR/.bashrc"
EOF
fi

#Clean up temporary files
trap "rm -f $PATH_BUFFER $ENV_BUFFER $BASHRC_BUFFER; kill 0" SIGINT
trap "rm -f $PATH_BUFFER $ENV_BUFFER $BASHRC_BUFFER" EXIT

exit 0;
