echo "Tapping kegs"
tap caskroom/cask
tap homebrew/dupes

echo "Checking for formulae updates"
update

echo "Checking for outdated formulae"
outdated

echo "Installing updated UNIX tools"
install coreutils
install binutils
install findutils --with-default-names
install gnu-indent --with-default-names
install gnu-sed --with-default-names
install gnu-tar --with-default-names
install gnu-which --with-default-names
install gnutls --with-default-names
install grep --with-default-names
install gzip
install wdiff --with-default-names
install xz
install watch

echo "Installing updated bash"
install bash
echo "\n\nRun \`brew info bash\` for complete installation instructions\n\n"

echo "Installing aux. development software"
install file-formula
install git
install less
install openssh --with-brewed-openssl
install rsync
install unzip
install tree
#install android-sdk

echo "Installing personal tools"
install bash-completion2
install awscli
install ansible
install docker
install git-crypt
install z

cleanup
