status "Tapping kegs"
tap caskroom/cask
tap homebrew/dupes

status "Checking for formulae updates"
update

status "Checking for outdated formulae"
outdated

status "Installing updated UNIX tools"
install coreutils
install binutils
install findutils --with-default-names
install gnu-indent --with-default-names
install gnu-sed --with-default-names
install gnu-tar --with-default-names
install gnu-which --with-default-names
install gnutls --with-default-names
install grep --with-default-names
install gzip
install wdiff --with-default-names
install xz

status "Installing updated bash"
install bash
warn "\n\nRun \`brew info bash\` for complete installation instructions\n\n"

status "Installing aux. development software"
install file-formula
install git
install less
install openssh --with-brewed-openssl
install rsync
install unzip
#install android-sdk
install julia
install fuse

status "Installing personal tools"
install bash-completion2
install awscli
install heroku-toolbelt
install ansible
install docker
install docker-machine
install git-crypt
install z

cleanup
